### ISSUE TITLE
design chatbot ui

### ISSUE THREAD

**Issue by sanjeeveasparan** [dto-btn/chatbot-ui#1]
design a simple ui for the chatbot using Flutter (done)

 Add customizable features and overall make it graphically pleasing

**Comment by GuillaumeTurcotte** [comment]
For next iteration let's try and add those things: 

(in priority order)

- source(s)
- feedback link (re-use one in current chatbot)
- feedback actions beside text bubbles
- toggle history
- multiple context windows (just like openai)
- prompt toggle (eng/fra)
- watermark



![Image](https://github.com/dto-btn/chatbot-ui/assets/78774/e4dfe74a-d0bd-44b2-9517-5d01c4b37411)
